services:
  openmu-startup:
    image: munique/openmu
    container_name: openmu-startup
    networks:
      - proxy
    ports:
      - "55901:55901"
      - "55902:55902"
      - "55903:55903"
      - "55904:55904"
      - "55905:55905"
      - "55906:55906"
      - "44405:44405"
      - "55980:55980"
    environment:
      DB_HOST: database
    working_dir: /app/
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.openmu.entrypoints=websecure"
      - "traefik.http.routers.openmu.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.openmu.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=.htpasswd"

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openmu
      POSTGRES_USER: postgres
    networks:
      - proxy
    ports:
      - "5432"
    volumes:
      - dbdata:/var/lib/postgresql/data #store data on volume

  traefik:
    image: traefik
    container_name: traefik
    restart: always
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data-traefik/traefik.yml:/traefik.yml:ro
      - ./data-traefik/acme.json:/acme.json
      - ./data-traefik/configurations:/configurations
      - "./.htpasswd:/.htpasswd"
    networks:
      - proxy
    labels:
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true

volumes:
  dbdata:
