services:
  openmu-startup:
    image: munique/openmu
    container_name: openmu-startup
    networks:
      - proxy
    ports:
      - "55901:55901"
      - "55902:55902"
      - "55903:55903"
      - "44405:44405"
      - "55980:55980"
    environment:
      DB_HOST: database
    working_dir: /app/
    volumes:
      - ./.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - database
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.openmu.entrypoints=web"
      - "traefik.http.routers.openmu.rule=Host(`admin.docker.localhost`)"
      - "traefik.http.routers.openmu.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.usersfile=.htpasswd"

  database:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: openmu
      POSTGRES_USER: postgres
    networks:
      - proxy
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data #store data on volume

  traefik:
    image: "traefik"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.htpasswd:/.htpasswd"
    networks:
      - proxy

networks:
  proxy:
    external: true

volumes:
  dbdata:
